# Tên của workflow, sẽ hiển thị trong tab "Actions" của GitHub
name: 'Cleanup: Delete Files'

# Cho phép chạy workflow này thủ công từ tab Actions
on:
  workflow_dispatch:
    inputs:
      # Định nghĩa một ô nhập liệu để bạn điền pattern của tệp cần xóa
      file_pattern:
        description: 'File pattern to delete (e.g., "*.log", "**/temp-*.txt")'
        required: true
        default: '*.html'

jobs:
  delete-files-job:
    runs-on: ubuntu-latest # Chạy trên một máy ảo Ubuntu

    # Cấp quyền cho Action để ghi vào repository
    permissions:
      contents: write

    steps:
      # Bước 1: Checkout code từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Tìm và xóa các tệp khớp với pattern bạn nhập
      - name: Find and delete files
        run: |
          # Lệnh find mạnh mẽ để tìm và xóa file
          # ${{ github.event.inputs.file_pattern }} sẽ lấy giá trị bạn nhập khi chạy workflow
          echo "Searching for files with pattern: ${{ github.event.inputs.file_pattern }}"
          
          # Sử dụng find để tìm và xargs để chuyển danh sách file cho lệnh rm
          # Dùng -print -delete để vừa in ra file bị xóa vừa thực hiện xóa
          find . -type f -name "${{ github.event.inputs.file_pattern }}" -print -delete
          
      # Bước 3: Commit và Push các thay đổi (việc xóa file) lên repository
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Kiểm tra xem có sự thay đổi nào không (có file nào bị xóa không)
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore: Deleted files based on pattern '${{ github.event.inputs.file_pattern }}'"
            git push
          else
            echo "No files to delete. Working tree clean."
          fi
